<a href="https://colab.research.google.com/github/Madhu678-coder/Pandas-Assignment/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Ch.MadhuKumar")

Ch.MadhuKumar

Importing libraries

In [ ]:
import pandas as pd

Reading the csv file

In [ ]:
df=pd.read_csv("/content/oecd_bli_2015.csv")

print the first 5 rows in the dataset

In [ ]:
df.head()

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,1.1,E,Estimated value
1,AUT,Austria,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,1.0,NaN,NaN
2,BEL,Belgium,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,2.0,NaN,NaN
3,CAN,Canada,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.2,NaN,NaN
4,CZE,Czech Republic,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.9,NaN,NaN

    Find missing values in a DataFrame and count them column-wise.

In [ ]:
df.isnull().sum()

LOCATION                    0
Country                     0
INDICATOR                   0
Indicator                   0
MEASURE                     0
Measure                     0
INEQUALITY                  0
Inequality                  0
Unit Code                   0
Unit                        0
PowerCode Code              0
PowerCode                   0
Reference Period Code    3292
Reference Period         3292
Value                       0
Flag Codes               2172
Flags                    2172
dtype: int64

    Filter rows in a DataFrame where a column value > 100.

In [ ]:
filter_df=df[df['Value']>100]
filter_df

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
327,AUS,Australia,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,31588.0,NaN,NaN
328,AUT,Austria,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,31173.0,NaN,NaN
329,BEL,Belgium,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,28307.0,NaN,NaN
330,CAN,Canada,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,29365.0,NaN,NaN
331,CZE,Czech Republic,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,18404.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743,EST,Estonia,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,503.0,NaN,NaN
1744,ISR,Israel,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,415.0,NaN,NaN
1745,RUS,Russia,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,436.0,NaN,NaN
1746,SVN,Slovenia,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,454.0,NaN,NaN
1747,OECD,OECD - Total,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,452.0,NaN,NaN

Group a DataFrame by a column and calculate the mean of each group.

In [ ]:
group_by=df.groupby('Indicator')['Value'].mean()
group_by

Indicator
Air pollution                                   19.889908
Assault rate                                     4.056757
Consultation on rule-making                      7.071560
Dwellings without basic facilities               2.532110
Educational attainment                          75.369369
Employees working very long hours                9.021441
Employment rate                                 64.994595
Homicide rate                                    2.928829
Household net adjusted disposable income     25879.322404
Household net financial wealth               40519.394495
Housing expenditure                             20.807339
Job security                                     5.688288
Life expectancy                                 79.714414
Life satisfaction                                6.553631
Long-term unemployment rate                      3.760734
Personal earnings                            34489.572973
Quality of support network                      89.532934
Rooms per person                                 1.662385
Self-reported health                            68.443243
Student skills                                 495.243243
Time devoted to leisure and personal care       14.858378
Voter turnout                                   70.383784
Water quality                                   82.657658
Years in education                              17.484685
Name: Value, dtype: float64

    Sorted a DataFrame by Country and value columns.

In [ ]:
sorted=df.sort_values(by=['Country','Value'],ascending=[True,False])
sorted

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
1211,AUS,Australia,JE_PEARN,Personal earnings,L,Value,HGH,High,USD,US Dollar,0,units,NaN,NaN,63976.0,E,Estimated value
436,AUS,Australia,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,units,NaN,NaN,62627.0,E,Estimated value
1137,AUS,Australia,JE_PEARN,Personal earnings,L,Value,MN,Men,USD,US Dollar,0,units,NaN,NaN,54780.0,NaN,NaN
1100,AUS,Australia,JE_PEARN,Personal earnings,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,50449.0,NaN,NaN
510,AUS,Australia,IW_HNFW,Household net financial wealth,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,47657.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2951,USA,United States,PS_SFRV,Assault rate,L,Value,WMN,Women,PC,Percentage,0,units,NaN,NaN,1.3,NaN,NaN
1055,USA,United States,JE_LTUR,Long-term unemployment rate,L,Value,HGH,High,PC,Percentage,0,units,NaN,NaN,1.1,E,Estimated value
29,USA,United States,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.1,NaN,NaN
66,USA,United States,HO_BASE,Dwellings without basic facilities,L,Value,MN,Men,PC,Percentage,0,units,NaN,NaN,0.1,E,Estimated value
102,USA,United States,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,units,NaN,NaN,0.1,E,Estimated value

Add a new column(Total) to a DataFrame that is a transformation of existing columns.by adding the value column twice

In [ ]:
df['Total']=df['Value']+df['Value']

In [ ]:
print(df['Total'])

0        2.20
1        2.00
2        4.00
3        0.40
4        1.80
        ...
3287    28.86
3288    28.48
3289    29.50
3290    28.24
3291    29.48
Name: Total, Length: 3292, dtype: float64

In [ ]:
df.head()

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags,Total
0,AUS,Australia,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,1.1,E,Estimated value,2.2
1,AUT,Austria,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,1.0,NaN,NaN,2.0
2,BEL,Belgium,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,2.0,NaN,NaN,4.0
3,CAN,Canada,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.2,NaN,NaN,0.4
4,CZE,Czech Republic,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.9,NaN,NaN,1.8

Loading the second dataset

In [ ]:
df1=pd.read_csv(r"/content/gdp_per_capita.csv",encoding='latin-1')

   Merge two DataFrames on a common column (inner join).

In [ ]:
merge=pd.merge(df,df1,on='Country',how='inner')
merge

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,...,Value,Flag Codes,Flags,Total,Subject Descriptor,Units,Scale,Country/Series-specific Notes,2015,Estimates Start After
0,AUS,Australia,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,1.10,E,Estimated value,2.20,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","50,961.87",2014.0
1,AUT,Austria,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,1.00,NaN,NaN,2.00,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","43,724.03",2015.0
2,BEL,Belgium,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,2.00,NaN,NaN,4.00,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","40,106.63",2014.0
3,CAN,Canada,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,0.20,NaN,NaN,0.40,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","43,331.96",2015.0
4,CZE,Czech Republic,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,0.90,NaN,NaN,1.80,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","17,256.92",2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3213,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.16,E,Estimated value,28.32,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","13,340.91",2014.0
3214,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.43,NaN,NaN,28.86,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","17,288.08",2014.0
3215,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.24,E,Estimated value,28.48,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","35,343.34",2015.0
3216,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.75,E,Estimated value,29.50,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","9,054.91",2015.0
3217,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.12,NaN,NaN,28.24,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...","20,732.48",2015.0